### ISSUE TITLE
Error troubleshooting

### ISSUE THREAD

**Issue by RandomCanadian12** [AkadenTK/superwarp#19]
Hey - sorry if this is the wrong place to ask this question but friend is getting error using this addon. I use it too but with no issue (I have 3 chars). When he uses it (with 5 chars), it functions but he gets this error:

superwarp: Lua runtime error: superwarp/sendall.lua:55: attempt to index a nil value

Any idea as to how to troubleshoot? Verified install is correct AND his chars still warp as intended, but he gets the error every time. 

Thanks, and superb addon.

**Comment by bjggi** [comment]
I also have this Problem since along time. I have the Error usually on 1 or 2 of my 6 chars when warping. I think always on the first or second char that warps.

I've noticed that increasing send_all_delay makes it happen more often, or kind always. Atm my Delay is at 1.9, when i put it 0.5 i dont get the error.

I'm happy to test things if u want me to.
