### ISSUE TITLE
Movement cancels Sortie teleports.

### ISSUE THREAD

**Issue by Zattano-XI** [AkadenTK/superwarp#59]
Movement procs an error that results in a delay/retrying message, but the addon doesn't proceed to resolve.  Not sure if its working at intended, but I've experienced the add-on being capable of queueing teleports of all types while approaching the porter prior.

I'll take a SS later and attach it after sortie.

Much appreciation for your time and efforts, this addition will be extremely helpful!

**Comment by AkadenTK** [comment]
It's very likely due to something specific for Sortie's warp system, and there's really nothing superwarp can do about it. The server detects when it gets movement packets from you and cancels it on the server end. There's a feature in superwarp to stop autorun before warping, that may help you. It would be VERY dangerous to stop the movement packets using superwarp.
